### ISSUE TITLE
UQRUG help

### ISSUE THREAD

**Issue by orchid00** [patrickaxe/Geoconvert#1]
Hi Patrick your package seems neat, what kind of help do you need?
You posted it on the UQRUG

**Comment by patrickaxe** [comment]
> Hi Patrick your package seems neat, what kind of help do you need?
> You posted it on the UQRUG

Hi Paula, it seems I encounter some issues in xy_lonla.R, as I am trying to convert from the Universal Transverse Mercator (UTM, in a form of x,y,z) to Geographic coordinate system (GCS, in a form of longitude, latitude, altitude). I am not sure if you can solve them. Could you help me to fill out # alternative part? This mini project is designed for GIS conversion in a part of my research project despite I knew ArcMap has this function already.  Cheers, Patrick
